# https://www.serverless.com/framework/docs-providers-aws-guide-functions
service: air-monitoring

provider:
  name: aws
  runtime: dotnet6
  region: eu-central-1
  memorySize: 512
  versionFunctions: false

package:
  individually: true

functions:
  data-providing:
    handler: AirMonitoring.DataProviding::AirMonitoring.DataProviding.Function::FunctionHandler
    package:
      artifact: AirMonitoring.DataProviding/bin/Release/net6.0/deploy-package.zip
    name: air-monitoring-${sls:stage}-data-providing
    url:
      cors: true
    events:
     - http:
         path: /measurements
         method: GET

  alerting:
    handler: AirMonitoring.Alerting::AirMonitoring.Alerting.Function::FunctionHandler
    package:
      artifact: AirMonitoring.Alerting/bin/Release/net6.0/deploy-package.zip
    name: air-monitoring-${sls:stage}-alerting
    # events:
      # - AwsSns: arn:aws:sns:eu-central-1:123456789012:AlertingTopic