service: service-users

provider:
  name: aws
  runtime: dotnet6
  region: eu-central-1
  memorySize: 512
  versionFunctions: false

package:
  artifact: service-users/bin/Release/net6.0/deploy-package.zip

functions:
  service-users:
    handler: service-users::service_users.Function::FunctionHandler
    name: ${sls:stage}-service-users
    url:
      cors:
        allowedOrigins:
            - http://localhost:4200
            - http://smarthome-front.s3-website.eu-central-1.amazonaws.com
        allowedHeaders:
            - Content-Type
            - X-Amz-Date
            - Authorization
            - X-Api-Key
            - X-Amz-Security-Token
            - X-Amz-User-Agent
        allowCredentials: false
    events:
     - http:
         path: /users
         method: GET